name: hr_management_system
description: A comprehensive HR management system

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  dio: ^5.4.0
  intl: ^0.19.0
  pdf: ^3.10.7
  file_picker: ^6.1.1
  flutter_slidable: ^3.0.1
  fl_chart: ^0.65.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  connectivity_plus: ^4.0.1
  workmanager: ^0.5.1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.6 